apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:latest #bitnami/zookeeper:3.6.2-debian-10-r124
          ports:
            - containerPort: 2181
          # readinessProbe:
          #   tcpSocket:
          #     port: 2181
          #   timeoutSeconds: 5
          #   periodSeconds: 5
          #   initialDelaySeconds: 40
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: '2181'
            - name: ZOOKEEPER_TICK_TIME
              value: '2000'
          resources:
            limits:
              memory: 256Mi
              cpu: "0.2"
            requests:
              memory: 256Mi
              cpu: "0.2"
