apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-ingress
spec:
  rules:
    - http:
        paths:
          - path: /api/client2
            pathType: Prefix
            backend:
              service:
                name: client2-service
                port:
                  number: 80
